spring:
  application:
    name: flight-booking-system

  datasource:
    url: jdbc:postgresql://localhost:5432/flight_booking
    username: booking_admin
    password: Book!ng2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

server:
  port: 8080